use_frameworks!

platform :ios, '8.0'

target 'LLSliderController_Example' do
  pod 'LLSliderController', :path => '../'

  target 'LLSliderController_Tests' do
    inherit! :search_paths

    
  end
end
